In [ ]:
import numpy as np

In [ ]:
a1d=np.array([1])# vector /1D array contains single pair of brackets []

In [ ]:
a2d=np.array([[[1],[2]],[[1],[2]]])#matrix/2d array contains 2 pairs of brackets
##a2d=np.array(n[1,2], [1,2]) this gives error

In [ ]:
a3d=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])#3d array contains 3 pairs of brackets
a3d

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [ ]:
type(a3d) # data Type, type to know data type

numpy.ndarray

In [ ]:
a3d.ndim # no. of dim

3

In [ ]:
a3d.dtype# type of entries, dimensionsal type

dtype('int64')

In [ ]:
a3d.size # no. of entries

8

In [ ]:
a3d=np.array([[[1.1],[2]],[[1],[2]]]) #it is float even if there's one entry is float
a3d.dtype

dtype('float64')

In [ ]:
import pandas as pd

In [ ]:
a2d=np.array([[1, 2],[3,4]])
df=pd.DataFrame(a2d) ##Data frame takes 2D  (2 series or 2d array ) Panda is madeup of numpy

In [ ]:
a2d.dtype

dtype('int64')

In [ ]:
df

0  1
0  1  2
1  3  4

In [ ]:
#creating arrays from np
ones=np.ones((2,2))# only ones, it takes shape
ones

array([[1., 1.],
       [1., 1.]])

In [ ]:
# only zeroes

zeros=np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Generating vector**

In [ ]:
#Generating a vector
range=np.arange(0,10,2)# start, stop,step
range

array([0, 2, 4, 6, 8])

In [ ]:
range=np.arange(6) #stop
range

array([0, 1, 2, 3, 4, 5])

# generating a matrix

In [ ]:
#generating a matrix randomly
random=np.random.rand(3,5)#it takes shape , range default from 0 to 1
random

array([[0.8643033 , 0.10382199, 0.50579986, 0.22741874, 0.87171979],
       [0.91702347, 0.94258902, 0.26770828, 0.07892904, 0.84592714],
       [0.52803576, 0.19894544, 0.33977844, 0.5721493 , 0.56396167]])

In [ ]:
random_mat= np.random.randint(0,50,(4,4))#start, stop, shape # for integers we have to give range
random_mat.sum()## this sum changes everytime we run it

370

#Random seed

In [ ]:
np.random.seed(seed=0)## it saves the output once executed
rand_mat=np.random.rand(3,5)
rand_mat

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [ ]:
rand_mat.sum()

9.042960048565472

In [ ]:
a3d

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [ ]:
arandom=np.random.randint(10,size=(2,3,4,5))## we have twice of 3 matrices of 4*5

In [ ]:
arandom[:2,:3,:3,:3]## slicing as of dimensions

array([[[[0, 1, 2],
         [0, 3, 2],
         [5, 9, 0]],

        [[2, 3, 4],
         [9, 1, 4],
         [2, 3, 0]],

        [[8, 8, 2],
         [0, 8, 8],
         [2, 8, 4]]],


       [[[0, 8, 5],
         [9, 6, 5],
         [8, 0, 4]],

        [[2, 8, 6],
         [1, 6, 8],
         [2, 3, 6]],

        [[6, 5, 8],
         [9, 7, 5],
         [5, 3, 3]]]])

# Data Manipulation

In [ ]:
a1d=np.array([1,2,3,4])

In [ ]:
ones=np.ones((2,4))

In [ ]:
a1d+ones ## first method
## np.add(a1d, ones) ## second method

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [ ]:
a1d-ones

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [ ]:
a1d*ones ### for division and multiplication both mat columns should be equal

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
a1d/ones

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
a1d//ones ## // is for whole number answer

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
np.square(a1d)

array([ 1,  4,  9, 16])

# **Aggregation is suming up in 1 word or number**

In [ ]:
sum(a1d) #first method
##np.sum(a1d)# second method

10

In [ ]:
rand= np.random.random(10000)## for generating 1D array

In [ ]:
%timeit  sum(rand)
%timeit  np.sum(rand)## np is 1000 time faster

1.29 ms ± 532 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
11.6 µs ± 971 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
np.min(rand)

0.00020407605031813603

In [ ]:
np.max(rand)

0.9999730227131577

In [ ]:
np.mean(rand) ## mean

0.49797292262314313

In [ ]:
np.var(rand) ## variance

0.08328474593116122

In [ ]:
np.std(rand) #standard deviation

0.2885909664753234

In [ ]:
np.random.seed(seed=0) # random is for one time use only
matrix1=np.random.randint(0,10000,(3,4))
matrix2=np.random.randint(0,10000,(3,4))

In [ ]:
matrix1*matrix2 ## entries wise multiplication  # both matrix must be equal

array([[ 6070504, 76475960,  9455808, 48070087],
       [ 4953825, 49050456, 30265533, 35455464],
       [14587272, 17589696,  3419955, 20472323]])

In [ ]:
matrix1.dot(matrix2.T) ## dot product with the transpose of matrix2
#in dot product the columns of matrix2 multiply with rows of matrix1

array([[140072359, 114582672, 109951163],
       [152575301, 119725278, 127459748],
       [ 69678884,  45745485,  56069246]])

In [ ]:
matrix1.reshape(3,4,1)# just relieve minor change

array([[[2732],
        [9845],
        [3264],
        [4859]],

       [[9225],
        [7891],
        [4373],
        [5874]],

       [[6744],
        [3468],
        [ 705],
        [2599]]])

**Exercise**

In [77]:
###Exercise to generate dataframe of 3columns and 5 rows

##practice

#df1=np.random.random(5)
#df2=np.random.random(5)
#df3=np.random.random(5)

#days=np.array(["Monday" ,"Tuesday","Wednesday","Thursday","Friday"])
#import pandas as pd
#df=pd.DataFrame({"Days":days,"Item1":df1,"Item2":df2,"Item3":df3})
#new_row=pd.DataFrame([["Sum",df["Item1"].sum(),df["Item2"].sum(),df["Item3"].sum()]])
#pd.concat([df,new_row])

#sum0=df["Item1"][0]+df["Item2"][0]+df["Item3"][0]
#sum1=df["Item1"][1]+df["Item2"][1]+df["Item3"][1]
#sum2=df["Item1"][2]+df["Item2"][2]+df["Item3"][2]
#sum3=df["Item1"][3]+df["Item2"][3]+df["Item3"][3]
#sum4=df["Item1"][4]+df["Item2"][4]+df["Item3"][4]

#day_sum=pd.Series([sum0,sum1,sum2,sum3,sum4])
#df['days_sum']=day_sum


**Solution**

In [97]:
np.random.seed(seed=0)
matrix=np.random.randint(20,size=(5,3))
matrix

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [98]:
import pandas as pd
df=pd.DataFrame(matrix,index=['Mon','Tuesday','WEd','Thurs','Fri'], columns=['ITem1','Item2','Item3'])## we generated
#dataframe out of a matrix
df

ITem1  Item2  Item3
Mon         12     15      0
Tuesday      3      3      7
WEd          9     19     18
Thurs        4      6     12
Fri          1      6      7

In [106]:
weekly_sales=np.array([[11,21,23,11,23]]).T # made 1D array and take tranpose to make it a column
df['weekly_sales']=weekly_sales
df

ITem1  Item2  Item3  weekly_sales
Mon         12     15      0            11
Tuesday      3      3      7            21
WEd          9     19     18            23
Thurs        4      6     12            11
Fri          1      6      7            23